spring:
  application:
    name: hairhub
  datasource:
    url:   jdbc:mysql://sql12.freesqldatabase.com:3306/sql12788423
    username: sql12788423
    password: CNzLQMtLYf
    # driverClassName:  com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  secret-key: 07BtAya6qMM8EA9eikWJLmwp3M7F6GWOCWTwgsUAxDHGOdxUsJodZQqQwcKWNO+z
  valid-duration: 3600  # in second (s)
  refreshable-duration: 36000 # in seconds (s)